version: "3.9"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGREST_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}
      MAXCONWAITINGTIME: ${MAXCONWAITINGTIME}
    volumes:
      - ./.data/docker-postgres:/var/lib/postgresql/data
    networks:
      - gollama-assistant
  pgweb:
    image: sosedoff/pgweb
    depends_on:
      - postgres
    environment:
      PGWEB_DATABASE_URL: postgres://username:password@postgres:5432/database-name?sslmode=disable
    ports:
      - 8085:8081
    restart: on-failure

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - ${POSTGRES_DB}

  redis-commander:
      image: rediscommander/redis-commander:latest
      environment:
        - REDIS_HOSTS=local:redis:6379
        - HTTP_USER=root
        - HTTP_PASSWORD=qwerty
      ports:
        - 8081:8081
      networks:
        - ${POSTGRES_DB}
      depends_on:
        - redis

  server:
    build: .
    networks:
      - go-ollama-advisor
    depends_on:
      - postgres
      - redis
    environment:
      LOG_FORMAT: json
      DB_HOST: db
      ADDR: "0.0.0.0:6969"
    ports:
      - 6969:6969

networks:
  go-ollama-advisor:
